version: '4.24.0'
services: 
  policy_api_server:
    image: nginx:latest
    ports: 
      - "9000:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./bundles:/usr/share/nginx/bundles  

  sql_server:
    image: postgres
    environment:
      - POSTGRES_DB=policies
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  opal_server:
    image: permitio/opal-server:latest
    environment:
      - OPAL_POLICY_REPO_URL=git@github.com:Hadi-Khouja/BA.git
      - OPAL_POLICY_REPO_SSH_KEY=-----BEGIN OPENSSH PRIVATE KEY-----_b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn_NhAAAAAwEAAQAAAQEAsLQC3RCpCe/GkMBKQwnlsgTDmT8L4t3yV3V8tdni141MGB1AhSWK_aMMfBZWnQO6iZH+U4bEtSSxKl82rARU2txwatfiL+MatGMOCyUAPN05yTN76DHmGnr5TDN_pjR+3MmnUAeJaeo5gslTLbHoCMI53vRiHf3jQmPO2MhgE81jQJIw3TNYvvYRbGNXbGFp5/_QNhLpJKo0N5fu68FANiC3i/BhpizAEhqE2Ev97C2f2W4VU/CWuDZyt2e5oZGE3iaBrdTeT_VsyWMvp3phhw5t1YdA84wNuD7lj6Gbtr6QtgQOciPtLk1AsR3SXjUltAKR1FrBanFKHU7i_+pnbcBK0nwAAA8gVTJK5FUySuQAAAAdzc2gtcnNhAAABAQCwtALdEKkJ78aQwEpDCeWyBM_OZPwvi3fJXdXy12eLXjUwYHUCFJYpowx8FladA7qJkf5ThsS1JLEqXzasBFTa3HBq1+Iv4_xq0Yw4LJQA83TnJM3voMeYaevlMM2mNH7cyadQB4lp6jmCyVMtsegIwjne9GId/eNCY87Y_yGATzWNAkjDdM1i+9hFsY1dsYWnn9A2EukkqjQ3l+7rwUA2ILeL8GGmLMASGoTYS/3sLZ/_ZbhVT8Ja4NnK3Z7mhkYTeJoGt1N5NWzJYy+nemGHDm3Vh0DzjA24PuWPoZu2vpC2BA5yI+_0uTUCxHdJeNSW0ApHUWsFqcUodTuL6mdtwErSfAAAAAwEAAQAAAQEAk5usELMMIirUOrMG_1f18jTsBkhBig39YI8sXBGog3mNAP5yf+xmjB2SHk4iyEMHHkiApZGc3JzsCjNDXmq336P_pnLb+UXZrJmjgoFqmWjGLRhHl3c9hIpm7ivYfpC3sQQa6fWByqJIrII1I6TL6hUldqO7Gs_atgxYRAnJQH/qgak/bAERPgkFb0PJMmF/luPTOXJAGKAkCVc6Km9W5jcQ/zpR8CzeY46sC_q1E3DbOfJlH49eOo6hWWoBKKXzwh94wTp3qQRrPlIEO6HJDQM4lQbgqL0I7gCsxkEXjmPq_zWaWpcxhBz+o3o75yM4o7Hj+6Pp7WDhiLFypHdv9DAyDQQAAAIAkUq3bKotMpZFVxqKwCi_mLzBkVHiEXFosS6CpzQw+BIxl8nlhVPtpp9MMB/tt9prbCXyRrhJ6Mu7vHFgEtcK4QYyPX_LOSByieQ3gtoe4UZPlxpX7xjhzJ1Y5vyW9ruIRGTqhM8fZbzg55GoG/arXHs53L0JY8ek3_zVZWV5mb4VsgAAAIEA6Yxby9+22oS+c+hzzT7GvHiBDdMFzjf8nj1uP2yZku1/Nc7vm0Fb_LxTTn8dd8e9QkyeuX+KhUx6vn2yLSZn8gm1+uCXXp+2dTB06QaQ84YGS9MzqDqHNfywbc7_vlNTTtDB41rQdErehLnvFMNpEVEhFRzQoIWIJV+EvRiRCJmXEAAACBAMGwsKdxFT4Ycl9x_Bi0dFHCodpAPzSMVbTGDwit8EbXUm8vmJpqe1L66jiy3mridv4BalaOgnjC3LlT7OUel2K_D/vDBudaAcI4yhhNUji17bInsB9F91RIFgBuQmc6yB7zcETPBGwNJ2jyS3HtnujiowSCV9_0vpknOu36h3eiqcPAAAAC29wYWxfc2VydmVyAQIDBAUGBw==_-----END OPENSSH PRIVATE KEY-----
      - OPAL_POLICY_REPO_MAIN_BRANCH=main
      - POLICY_REPO_CLONE_FOLDER_PREFIX=/policy
      - OPAL_POLICY_REPO_POLLING_INTERVAL=30
      #- OPAL_POLICY_BUNDLE_URL=http://policy_api_server
      #- OPAL_POLICY_SOURCE_TYPE=API
      #- OPAL_POLICY_REPO_POLLING_INTERVAL=30
      - OPAL_DATA_CONFIG_SOURCES={"config":{"entries":[{"url":"postgresql://admin@sql_server:5432/policies","config":{"fetcher":"PostgresFetchProvider","query":"SELECT * from users;","connection_params":{"password":"postgres"}},"topics":["policy_data"],"dst_path":"users"},{"url":"postgresql://admin@sql_server:5432/policies","config":{"fetcher":"PostgresFetchProvider","query":"SELECT * FROM groups;","connection_params":{"password":"postgres"}},"topics":["policy_data"],"dst_path":"groups"},{"url":"postgresql://admin@sql_server:5432/policies","config":{"fetcher":"PostgresFetchProvider","query":"SELECT memberOf.user_id, users.name AS username, memberOf.group_id, groups.name FROM memberOf JOIN groups ON memberOf.group_id = groups.group_id JOIN users ON memberOf.user_id = users.user_id;","connection_params":{"password":"postgres"}},"topics":["policy_data"],"dst_path":"members"}]}}
    ports:
      - "7002:7002"
    depends_on:
      - policy_api_server

  opal_client:
    image: custom-opal-client
    build: 
      context: .
      dockerfile: custom-opal-client.Dockerfile
    environment:
      - OPAL_SERVER_URL=http://opal_server:7002
      - OPAL_LOG_FORMAT_INCLUDE_PID=true
      - OPAL_INLINE_OPA_LOG_FORMAT=http
      - OPAL_FETCH_PROVIDER_MODULES=opal_common.fetcher.providers,opal_fetcher_postgres.provider
    ports:
      - "7766:7000"
      - "8181:8181"
    depends_on:
      - opal_server
      - sql_server
    command: sh -c "exec ./wait-for.sh opal_server:7002 sql_server:5432 --timeout=20 -- ./start.sh"

#  policy_app:
#    image: policy-app
#    build: 
#      context: .
#      dockerfile: frontend.Dockerfile
#    ports:
#      - "8000:8000"