POST http://localhost:7002/webhook HTTP/1.1
Content-Type: application/json
User-Agent: GitLab/16.2.4
X-Gitlab-Event: Push Hook
X-Gitlab-Webhook-UUID: eea3aac6-115b-4e88-8af5-324d941888ab
X-Gitlab-Instance: https://git.d-velop.de
X-Gitlab-Event-UUID: da1dbd9c-e190-4cd2-be51-7ab9c95f483e
X-Gitlab-Token: KrbCciQSUjO6hVyWGo9-sW1TDV66-Ge8Jn-A-p-xffo

{
  "object_kind": "push",
  "event_name": "push",
  "before": "7855bbfb08d65256d19a32189b6726f2b2edfe0d",
  "after": "02493c0569091781ad139671592c261d6abe1bc3",
  "ref": "refs/heads/main",
  "ref_protected": true,
  "checkout_sha": "02493c0569091781ad139671592c261d6abe1bc3",
  "message": null,
  "user_id": 1031,
  "user_name": "Khouja Hadi",
  "user_username": "hkho",
  "user_email": null,
  "user_avatar": "https://secure.gravatar.com/avatar/4f12f251f7a7bb7bdbb23c479b7b7ecf?s=80&d=identicon",
  "project_id": 18364,
  "project": {
    "id": 18364,
    "name": "opa",
    "description": null,
    "web_url": "https://git.d-velop.de/hkho/opa",
    "avatar_url": null,
    "git_ssh_url": "git@git.d-velop.de:hkho/opa.git",
    "git_http_url": "https://git.d-velop.de/hkho/opa.git",
    "namespace": "Khouja Hadi",
    "visibility_level": 10,
    "path_with_namespace": "hkho/opa",
    "default_branch": "main",
    "ci_config_path": "",
    "homepage": "https://git.d-velop.de/hkho/opa",
    "url": "git@git.d-velop.de:hkho/opa.git",
    "ssh_url": "git@git.d-velop.de:hkho/opa.git",
    "http_url": "https://git.d-velop.de/hkho/opa.git"
  },
  "commits": [
    {
      "id": "02493c0569091781ad139671592c261d6abe1bc3",
      "message": "compose yaml\n",
      "title": "compose yaml",
      "timestamp": "2023-10-13T13:57:37+02:00",
      "url": "https://git.d-velop.de/hkho/opa/-/commit/02493c0569091781ad139671592c261d6abe1bc3",
      "author": {
        "name": "Khouja Hadi",
        "email": "[REDACTED]"
      },
      "added": [

      ],
      "modified": [
        "docker-compose.yaml",
        "nginx/nginx.conf"
      ],
      "removed": [

      ]
    },
    {
      "id": "4721c5cfde426dcfdb2f8cf00f615a60b6f89d2c",
      "message": "policy readded\n",
      "title": "policy readded",
      "timestamp": "2023-10-13T13:12:25+02:00",
      "url": "https://git.d-velop.de/hkho/opa/-/commit/4721c5cfde426dcfdb2f8cf00f615a60b6f89d2c",
      "author": {
        "name": "Khouja Hadi",
        "email": "[REDACTED]"
      },
      "added": [
        ".gitignore"
      ],
      "modified": [
        "policy/user_managment.rego"
      ],
      "removed": [
        "Dockerfile"
      ]
    },
    {
      "id": "7855bbfb08d65256d19a32189b6726f2b2edfe0d",
      "message": "Merge branch 'main' of https://git.d-velop.de/hkho/opa\n",
      "title": "Merge branch 'main' of https://git.d-velop.de/hkho/opa",
      "timestamp": "2023-10-12T15:51:54+02:00",
      "url": "https://git.d-velop.de/hkho/opa/-/commit/7855bbfb08d65256d19a32189b6726f2b2edfe0d",
      "author": {
        "name": "Khouja Hadi",
        "email": "[REDACTED]"
      },
      "added": [

      ],
      "modified": [
        "policy/user_managment.rego"
      ],
      "removed": [

      ]
    }
  ],
  "total_commits_count": 3,
  "push_options": {
  },
  "repository": {
    "name": "opa",
    "url": "git@git.d-velop.de:hkho/opa.git",
    "description": null,
    "homepage": "https://git.d-velop.de/hkho/opa",
    "git_http_url": "https://git.d-velop.de/hkho/opa.git",
    "git_ssh_url": "git@git.d-velop.de:hkho/opa.git",
    "visibility_level": 10
  }
}